01 ind-state.
   02 ind-ptr usage pointer.
   02 ind-cap binary-long unsigned.
   02 ind-count binary-long unsigned.
   02 ind-nparams binary-long unsigned.
   02 ind-lparams binary-long unsigned.
   02 ind-levels binary-long unsigned.
   02 ind-params binary-long unsigned.
   02 ind-universe binary-long unsigned.
   02 ind-all binary-long unsigned.
   02 ind-is-rec binary-char unsigned.
   02 ind-reflexive binary-char unsigned.
   02 ind-elim-level binary-long unsigned.
   02 ind-rec-levels binary-long unsigned.
   02 ind-rec-lparams binary-long unsigned.
   02 ind-motives binary-long unsigned.
   02 ind-minors binary-long unsigned.
   02 ind-k binary-char unsigned.
   02 ind-allow-primitive binary-char unsigned.
   02 ind-original-count binary-long unsigned.
   02 ind-original-all binary-long unsigned.
   02 ind-nested-params binary-long unsigned.
   02 ind-nested-ptr usage pointer.
   02 ind-nested-cap binary-long unsigned.
   02 ind-nested-count binary-long unsigned.
   02 ind-nested-next binary-long unsigned.
   02 ind-saved-bindings binary-long unsigned.
   02 ind-restored-decls binary-long unsigned.
