*> Generated by scripts/generate-primitive-quotes.py; do not edit.
01 reflection-context.
   02 rc-r-type binary-long unsigned.
   02 rc-r-true binary-long unsigned.
   02 rc-r-false binary-long unsigned.
   02 rc-r-dec binary-long unsigned.
   02 rc-r-ite binary-long unsigned.
   02 rc-r-dite binary-long unsigned.
   02 rc-c-prop binary-long unsigned.
   02 rc-c-dec binary-long unsigned.
   02 rc-c-proof binary-long unsigned.
   02 rc-as-bool binary-long unsigned.
   02 rc-p binary-long unsigned.
   02 rc-hyp binary-long unsigned.
   02 rc-a binary-long unsigned.
   02 rc-b binary-long unsigned.
   02 rc-x binary-long unsigned.
   02 rc-y binary-long unsigned.
   02 rc-hy binary-long unsigned.
   02 rc-fuel binary-long unsigned.
   02 rc-h binary-long unsigned.
   02 rc-value binary-long unsigned.
   02 rc-go binary-long unsigned.
01 reflection-slots redefines reflection-context.
   02 reflection-slot binary-long unsigned occurs 21.
