01 kernel-state.
   02 verdict binary-long signed.
   02 name-count binary-long unsigned.
   02 name-cap binary-long unsigned.
   02 name-ptr usage pointer.
   02 name-hcap binary-long unsigned.
   02 name-hptr usage pointer.
   02 byte-count binary-long unsigned.
   02 byte-cap binary-long unsigned.
   02 byte-ptr usage pointer.
   02 level-count binary-long unsigned.
   02 level-cap binary-long unsigned.
   02 level-ptr usage pointer.
   02 level-hcap binary-long unsigned.
   02 level-hptr usage pointer.
   02 recursion-limit binary-long unsigned.
   02 expr-count binary-long unsigned.
   02 expr-cap binary-long unsigned.
   02 expr-ptr usage pointer.
   02 expr-hcap binary-long unsigned.
   02 expr-hptr usage pointer.
   02 list-count binary-long unsigned.
   02 list-cap binary-long unsigned.
   02 list-ptr usage pointer.
   02 list-hcap binary-long unsigned.
   02 list-hptr usage pointer.
   02 blob-count binary-long unsigned.
   02 blob-cap binary-long unsigned.
   02 blob-ptr usage pointer.
   02 blob-hcap binary-long unsigned.
   02 blob-hptr usage pointer.
   02 decl-count binary-long unsigned.
   02 decl-cap binary-long unsigned.
   02 decl-ptr usage pointer.
   02 local-count binary-long unsigned.
   02 local-cap binary-long unsigned.
   02 local-ptr usage pointer.
   02 fuel-rec-depth binary-long unsigned.
   02 fuel-whnf binary-long unsigned.
   02 fuel-whnf-eager binary-long unsigned.
   02 fuel-lazy-delta binary-long unsigned.
   02 fuel-eta-expand binary-long unsigned.
   02 fuel-inductive binary-long unsigned.
   02 quot-initialized binary-char unsigned.
   02 replay-has-strings binary-char unsigned.
   02 replay-stamp binary-long unsigned.
   02 export-count binary-long unsigned.
   02 rule-count binary-long unsigned.
   02 rule-cap binary-long unsigned.
   02 rule-ptr usage pointer.
   02 checked-count binary-long unsigned.
   02 tc-context.
copy "tc-context.cpy".
