#!/usr/bin/env python3
"""Compile primitive-quotes.lean JSON into immutable COBOL expression tables.

Usage: lake env lean --run tests/primitive-quotes.lean > quotes.jsonl
       python3 scripts/generate-primitive-quotes.py quotes.jsonl
Run Lean in the pinned lean4lean checkout. No Lean or JSON dependency at runtime.
"""
import json
from pathlib import Path
import sys

OUTPUTS = {}

def emit(path, text):
    OUTPUTS[path] = text


ROOT = Path(__file__).resolve().parents[1]
SLOTS = ['r-type', 'r-true', 'r-false', 'r-dec', 'r-ite', 'r-dite',
         'c-prop', 'c-dec', 'c-proof', 'as-bool', 'p', 'hyp', 'a', 'b',
         'x', 'y', 'hy', 'fuel', 'h', 'value', 'go']
nodes = []
index = {}


def node(family, kind=0, mask=0, a=0, b=0, c=0, d=0, text=''):
    key = (family, kind, mask, a, b, c, d, text)
    if key not in index:
        index[key] = len(nodes) + 1
        nodes.append(key)
    return index[key]


def name(n):
    return node('N', text=n)


def level(e):
    k = e[0]
    if k == 0:
        return node('L')
    if k == 1:
        return node('L', k, 1, level(e[1]))
    if k in [2, 3]:
        return node('L', k, 3, level(e[1]), level(e[2]))
    if k == 4:
        return node('L', k, 1, name(e[1]))
    raise ValueError(e)


def levels(es):
    if not es:
        return 0
    return node('S', 0, 3, level(es[0]), levels(es[1:]))


def expr(e):
    k = e[0]
    if k == 0:
        return node('E', k, a=e[1])
    if k == 1:
        return node('E', k, 1, level(e[1]))
    if k == 2:
        return node('E', k, 3, name(e[1]), levels(e[2]))
    if k in [3, 4, 5]:
        return node('E', k, 3, expr(e[1]), expr(e[2]))
    if k == 6:
        return node('E', k, 7, expr(e[1]), expr(e[2]), expr(e[3]), int(e[4]))
    if k == 7:
        return node('E', k, 5, name(e[1]), e[2], expr(e[3]))
    if k in [8, 9]:
        literal = node('B', a=len(e[1].encode()), text=e[1])
        return node('E', k, 1, literal)
    if k == 10:
        return node('H', a=SLOTS.index(e[1].removeprefix('«').removesuffix('»')) + 1)
    if k == 11:
        return node('E', k, 1, expr(e[1]))
    raise ValueError(e)


quotes = [(r['name'], expr(r['expr'])) for line in Path(sys.argv[1]).read_text().splitlines()
          if (r := json.loads(line))]
copy = ROOT / 'src/copy'
header = '*> Generated by scripts/generate-primitive-quotes.py; do not edit.\n'
body = header + '01 reflection-context.\n'
body += ''.join(f'   02 rc-{slot} binary-long unsigned.\n' for slot in SLOTS)
body += '01 reflection-slots redefines reflection-context.\n'
body += f'   02 reflection-slot binary-long unsigned occurs {len(SLOTS)}.\n'
emit(copy / 'reflection.cpy', body)
emit(copy / 'quote-cache.cpy', header + f'01 quote-cache.\n   02 quote-memo binary-long unsigned occurs {len(nodes)}.\n')
body = header + '01 quote-instructions.\n'
for family, kind, mask, a, b, c, d, text in nodes:
    assert len(text.encode()) <= 128 and '\n' not in text, text
    fields = f'{family}{kind:02d}{mask:02d}{a:06d}{b:06d}{c:06d}{d:06d}' + text
    body += f"   02 filler pic x(157) value '{fields.replace(chr(39), chr(39)*2)}'.\n"
body += f'''01 quote-table redefines quote-instructions.
   02 quote-instruction occurs {len(nodes)}.
      03 quote-family pic x.
      03 quote-kind pic 99.
      03 quote-mask pic 99.
      03 quote-arg pic 9(6) occurs 4.
      03 quote-text pic x(128).
'''
emit(copy / 'quote-data.cpy', body)
body = header + 'evaluate quotation-name\n'
body += ''.join(f"  when '{name}' move {root} to root-id\n" for name, root in quotes)
body += '  when other move 3 to verdict\nend-evaluate\n'
emit(copy / 'quote-select.cpy', body)
print(f'{len(quotes)} quotations, {len(nodes)} shared instructions')

for path, text in OUTPUTS.items():
    if '--check' in sys.argv:
        if not path.exists() or path.read_text() != text:
            raise SystemExit(f'Generated quotation data differs: {path}')
    else:
        path.write_text(text)
